### ISSUE TITLE
Request the permission to translate & reupload

### ISSUE THREAD

**Issue by PopChicken** [Mantas-2155X/AI_BetterHScenes#1]
Many Chinese players love your plugin, but some are confused with English. I want to request your permission to translate it and upload it to zodgame forum. Thank you!

**Comment by Mantas-2155X** [comment]
Hello,

I was planning on making a Chinese version, but I'm currently very busy and unable to update my plugins for a while. 
So feel free to do that. Please include a link somewhere to the original post if possible.

**Comment by PopChicken** [comment]
Sure. I'll make it these days.
Besides, I saw a user named 2155X on zodgame forum, is that you? I've comment under your post lol.

**Comment by Mantas-2155X** [comment]
Yes, that should be me. I've not been on the site for a while. Will return once I'm ready to post updates :)
